spring.application.name=murciaecomerce
spring.datasource.url=jdbc:postgresql://localhost:5432/backend_db
spring.datasource.username=backend_usr
spring.datasource.password=backend_pwd
spring.datasource.driver-class-name=org.postgresql.Driver
